### ISSUE TITLE
Refactoring plans

### ISSUE THREAD

**Issue by samoht** [mirage/irmin#1340]
Here is a list of refactoring improvements:

- [x] move Metadata to their own file #1336
- [x] move Store_property to their own file #1337
- [x] clean-up Sync / Sync_ext #1338 
- [x] NO CAPS #1341 
- [x] move content_addressable/append_only/read_write to their own files  #1342
  - remove s.ml 
  - move closable functions to store_property
- [x] add signatures for read-only stores #1343  
- [x] use `include …._intf.Sigs (* @inline *)` consistenltly #1344 
- [x] refactor irmin-git #1347
- [x] extended S signatures (instead of repeating include BATCH, include OF_CONFIG, etc.) #1345
- [x] simplify irmin-layer (there's an ID functor) #1349 #1351
- [x] Refactor Maker signatures #1369 
- [x] cleanup irmin-pack
  - [x]  extract Version #1352 
  - [x] add missing headers #1353 
  - [x] move exceptions to s.ml #1354
  - [x] move logging, `++` and `--` to import.ml #1355 #1375 
  - [x] Rename Inode.Elt -> Inode.Raw and decode_bin to decode_raw and VAL to Value #1356
  - [x] Rename Inode.Inter to Inode.Internal #1356
  - [x] Remove most of the include/open #1372
  - [x] rename config.ml conf.ml #1370
  - [x] create migrate.ml #1374
  - [x] remove extra open Logs modules #1375
  - [x] move store.Checks in to Checks #1376
  - [x] rename pack.ml content_addressable.ml #1377 
  - [x] add atomic_write.ml #1378
  - [x] remove store.ml #1379 
  - [x] remove closeable.ml #1381
- [ ] move closeable functors to irmin (from irmin-git and irmin-http and irmin-pack) #1348
