### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by icristescu** [mirage/irmin#1695]
## Irmin release task list 

- [x] upstream merkle proofs
  - [x] #1711 
  - [x] #1712
  - [x] Merkle Proofs in inode #1716 
  - [x] Refactor cache usages in tree #1724 
  - [x] In `node.ml` fix problem causing `assert false` in `of_entry` https://github.com/mirage/irmin/pull/1737
  - [x] #1744 
  - [x] #1745
  - [x] #1746
  - [x] #1747
  - [x] #1748 
  - [x] #1749
  - [x] #1755
  - [x] Merkle Proofs everywhere https://github.com/mirage/irmin/pull/1729
- [x] refactor inodes:
  - [x] fix length in V2 entries https://github.com/mirage/irmin/pull/1736
  - [x] remove `Truncated` https://github.com/mirage/irmin/pull/1659#discussion_r773093699 -  we actually need this in the merkle proof
- [x] irmin-unix cli https://github.com/mirage/irmin/pull/1608
- [x] remove git_paf https://github.com/mirage/irmin/pull/1632
- [x] prehash collisions fix https://github.com/mirage/irmin/issues/1304
- [x] #1728
- [x] #1767
- [x] check that everything compiles for https://github.com/roburio/dns-primary-git

Not blocking the release:
- [ ] update irmin tutorial
- [x] investigate disk size when using the `index never` strategy
- [ ] improve snapshots:
   - [ ] use the `index never` strategy during the import
   - [ ] expose inodes in the snapshot format to reduce memory consumption 
- [ ] irmin-pack: Strengthen crash and SWMR consistencies https://github.com/mirage/irmin/pull/1690
- [ ] merkle proofs
  - [ ] Fail during `produce` if calling a tree function unhandled by `verify`
  - [ ] Fail during `produce` if `P.Node.find` or `P.Contents.find` returns `None`
  - [ ] Streamline `merge_env` and `Env.copy`. It should fail in certain situations.

**Comment by zshipko** [comment]
I have a branch with tutorial updates for the Irmin 3 release: https://github.com/mirage/irmin.org/pull/89 - it will probably need some additional work before I would consider it done.
