### ISSUE TITLE
Release 2.10.2

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1731]
## Irmin release task list 

- [x] Fix segments of streamed extender (#1742)
- [x] Fix streamed proofs with large stable inodes (#1741)
- [x] LRU grows too much in Ithaka (#1732) - setting the `lru_size` from tezos code directly (https://gitlab.com/tezos/tezos/-/merge_requests/4310) is good enough for now, let's postpone this for later releases

**Comment by CraigFe** [comment]
@Ngoguey42, @icristescu: Just to confirm, are we good to go with this release now? If so, I'll take care of it.

**Comment by Ngoguey42** [comment]
Yes, we are good to go. Thank you
