### ISSUE TITLE
Tracking: layered store 2022 Q2

### ISSUE THREAD

**Issue by tomjridge** [mirage/irmin#1824]
This is an issue to track the new layered store implementation. The previous issue (for Q1) was #1753 

The current branch: https://github.com/tomjridge/irmin/tree/2022-05-17_layers_on_3.2.1 (this is kept in sync with Victor's branch below)

A recent tezos branch, with additional code to trigger gc every so often, is here: https://github.com/tomjridge/tezos/tree/2022-03-14_layers

Victor's branch, to integrate layers into Tezos properly, is here: https://gitlab.com/nomadic-labs/tezos/-/tree/vicall@tomjridge@layered_store ; Victor rebases this quite often against tezos master branch

Todo:

- [ ] Benchmarking; perhaps refinement of the code (eg calculation of reachable objects)
- [ ] Proper testing and performance measuring for Tezos use case - they want to GC every cycle, but only keep the last 6 cycles; how does this affect timings for Repo.iter? What is the impact on IO? Also, what is the space overhead? (presumably we need an extra 6 cycles worth of storage if we are GC'ing from 6 cycles ago - this will be copied to the next suffix file; and on top of this we have the sparse file overhead for live objects from the commit, 3GB currently)
- [ ] "Hardening" pass, where all the FIXMEs are addressed, corner cases fixed, etc. Especially to fix all the corner cases where storage may run out.
- [ ] Merging into main irmin repo
- [ ] Improve docs; incorporate https://hackmd.io/MCHISJcSRTe9RWvstRqvlw and any other previous documentation (at the moment, it is spread over various web docs, the prototype, the code etc; needs tidying)

Relevant issues: those tagged with "feature/layered-store"
