### ISSUE TITLE
Failing UTs on GC branch

### ISSUE THREAD

**Issue by Ngoguey42** [mirage/irmin#1874]
- [ ] `dict-files            1   RO dict.` #1873
- [x] `pack-files            2   close.`
- [x] `pack-files            4   readonly sync, index flush.`
- [x] `existing stores       0   Test index reconstruction.` #1877
- [ ] `existing stores       1   Test integrity check.`
- [x] `existing stores       2   Test integrity check for in...` #1877
- [ ] `version-bump          0   test_RO_no_version_bump.`
- [ ] `version-bump          1   test_RW_no_version_bump.`
- [ ] `version-bump          2   test_RW_version_bump.`
- [x] `snapshot              0   in memory.` #1872
- [x] `snapshot              1   on disk.` #1872
- [x] `PACK { Tezos }        1   Basic operations on contents.` #1876
- [x] `PACK { Tezos }        2   Basic operations on nodes.` #1876
- [x] `PACK { Tezos }        3   Basic operations on commits.` #1876
- [x] `PACK { Tezos }       13   High-level store operations.`
- [x] `PACK { Small_nodes }  1   Basic operations on contents.` #1876
- [x] `PACK { Small_nodes }  2   Basic operations on nodes.` #1876
- [x] `PACK { Small_nodes }  3   Basic operations on commits.` #1876
- [x] `PACK { Small_nodes } 13   High-level store operations.`
- [x] `replay             0   replay_1_commit.`
